"""
Studex — lug'at ma'lumotlar bazasi (STUDEX.py'dan ko'chirildi)
"""

# Kengaytirilgan va boyitilgan A1-A2 darajasidagi sara so'zlar bazasi (Jami: 300 ta so'z)
VOCABULARY_DATA = [
    {"word": "Book", "translation": "kitob", "level": "A1", "example": "I read a book every evening."},
    {"word": "Water", "translation": "suv", "level": "A1", "example": "Please give me a glass of water."},
    {"word": "Friend", "translation": "doʻst", "level": "A1", "example": "She is my best friend."},
    {"word": "School", "translation": "maktab", "level": "A1", "example": "We go to school by bus."},
    {"word": "Happy", "translation": "baxtli / xursand", "level": "A1", "example": "Today is a happy day."},
    {"word": "Family", "translation": "oila", "level": "A1", "example": "I love my family very much."},
    {"word": "Time", "translation": "vaqt", "level": "A1", "example": "What time is it now?"},
    {"word": "City", "translation": "shahar", "level": "A1", "example": "Tashkent is a big city."},
    {"word": "Cat", "translation": "mushuk", "level": "A1", "example": "My cat loves to sleep on the sofa."},
    {"word": "House", "translation": "uy", "level": "A1", "example": "They live in a beautiful house."},
    {"word": "Milk", "translation": "sut", "level": "A1", "example": "I drink a glass of milk every morning."},
    {"word": "Sun", "translation": "quyosh", "level": "A1", "example": "The sun is very bright today."},
    {"word": "Car", "translation": "mashina", "level": "A1", "example": "My father drives a white car."},
    {"word": "Tree", "translation": "daraxt", "level": "A1", "example": "There is a big tree in our garden."},
    {"word": "Doctor", "translation": "shifokor", "level": "A1", "example": "The doctor helped the sick child."},
    {"word": "Window", "translation": "deraza", "level": "A1", "example": "Please open the window, it is hot inside."},
    {"word": "Boy", "translation": "bola / oʻgʻil bola", "level": "A1", "example": "That boy is my classmate."},
    {"word": "Girl", "translation": "qiz bola", "level": "A1", "example": "The girl is playing with her doll."},
    {"word": "Morning", "translation": "ertalab / tong", "level": "A1", "example": "I wake up early in the morning."},
    {"word": "Night", "translation": "tun / kecha", "level": "A1", "example": "Good night, see you tomorrow!"},
    {"word": "Bread", "translation": "non", "level": "A1", "example": "Can you buy some fresh bread?"},
    {"word": "Chair", "translation": "stul", "level": "A1", "example": "Please sit on this chair."},
    {"word": "Teacher", "translation": "oʻqituvchi", "level": "A1", "example": "Our English teacher is very kind."},
    {"word": "Door", "translation": "eshik", "level": "A1", "example": "Don't forget to close the door."},
    {"word": "Dog", "translation": "kuchuk / it", "level": "A1", "example": "My dog barks when someone comes."},
    {"word": "Fish", "translation": "baliq", "level": "A1", "example": "The fish is swimming in the water."},
    {"word": "Pen", "translation": "ruchka", "level": "A1", "example": "Can I borrow your pen, please?"},
    {"word": "Room", "translation": "xona", "level": "A1", "example": "My room is always clean and tidy."},
    {"word": "Apple", "translation": "olma", "level": "A1", "example": "An apple a day keeps the doctor away."},
    {"word": "Beautiful", "translation": "go'zal, chiroyli", "level": "A1", "example": "She has a beautiful voice."},
    {"word": "Big", "translation": "katta", "level": "A1", "example": "They live in a big city."},
    {"word": "Breakfast", "translation": "nonushta", "level": "A1", "example": "What did you eat for breakfast?"},
    {"word": "Brother", "translation": "aka / uka", "level": "A1", "example": "My brother plays football very well."},
    {"word": "Child", "translation": "bola", "level": "A1", "example": "The child is sleeping peacefully."},
    {"word": "Cold", "translation": "sovuq", "level": "A1", "example": "The weather is very cold today."},
    {"word": "Day", "translation": "kun", "level": "A1", "example": "Have a wonderful day ahead!"},
    {"word": "Dinner", "translation": "kechki ovqat", "level": "A1", "example": "We eat dinner together at 7 PM."},
    {"word": "Easy", "translation": "oson", "level": "A1", "example": "This English test is very easy."},
    {"word": "Father", "translation": "ota", "level": "A1", "example": "My father works at a bank."},
    {"word": "Food", "translation": "ovqat, taom", "level": "A1", "example": "I love Italian food like pizza."},
    {"word": "Garden", "translation": "bog', tomorqa", "level": "A1", "example": "There are beautiful flowers in the garden."},
    {"word": "Good", "translation": "yaxshi", "level": "A1", "example": "Reading books is a good habit."},
    {"word": "Hot", "translation": "issiq", "level": "A1", "example": "Be careful, the coffee is very hot."},
    {"word": "Job", "translation": "ish, kasb", "level": "A1", "example": "He is looking for a new job."},
    {"word": "Language", "translation": "til", "level": "A1", "example": "Learning a foreign language is fun."},
    {"word": "Life", "translation": "hayot", "level": "A1", "example": "Life is full of wonderful surprises."},
    {"word": "Man", "translation": "erkak kishi", "level": "A1", "example": "That man is our new neighbor."},
    {"word": "Mother", "translation": "ona", "level": "A1", "example": "My mother cooks delicious food."},
    {"word": "New", "translation": "yangi", "level": "A1", "example": "I bought a new phone yesterday."},
    {"word": "Old", "translation": "eski, qari", "level": "A1", "example": "This is an old traditional house."},
    {"word": "Paper", "translation": "qog'oz", "level": "A1", "example": "Can you give me a piece of paper?"},
    {"word": "Question", "translation": "savol", "level": "A1", "example": "If you have a question, please ask."},
    {"word": "Rain", "translation": "yomg'ir", "level": "A1", "example": "I like walking under the rain."},
    {"word": "Shoes", "translation": "poyabzal, oyoq kiyim", "level": "A1", "example": "Your new shoes look very clean."},
    {"word": "Sister", "translation": "opa / singil", "level": "A1", "example": "My sister is a talented artist."},
    {"word": "Sky", "translation": "osmon", "level": "A1", "example": "The sky is completely clear tonight."},
    {"word": "Small", "translation": "kichik, mayda", "level": "A1", "example": "He lives in a small apartment."},
    {"word": "Student", "translation": "talaba, o'quvchi", "level": "A1", "example": "She is a hard-working student."},
    {"word": "Table", "translation": "stol", "level": "A1", "example": "Put the keys on the table, please."},
    {"word": "Village", "translation": "qishloq", "level": "A1", "example": "My grandparents live in a beautiful village."},
    {"word": "Woman", "translation": "ayol kishi", "level": "A1", "example": "The woman over there is a famous doctor."},
    {"word": "Always", "translation": "har doim", "level": "A1", "example": "I always do my homework in the evening."},
    {"word": "Never", "translation": "hech qachon", "level": "A1", "example": "He never eats meat because he is a vegetarian."},
    {"word": "Sometimes", "translation": "ba'zan", "level": "A1", "example": "Sometimes we go out for a walk."},
    {"word": "Often", "translation": "tez-tez", "level": "A1", "example": "She often visits her grandmother."},
    {"word": "Usually", "translation": "odatda", "level": "A1", "example": "I usually wake up at 7 o'clock."},
    {"word": "Air", "translation": "havo", "level": "A1", "example": "We need fresh air to stay healthy."},
    {"word": "Animal", "translation": "hayvon", "level": "A1", "example": "The lion is a wild animal."},
    {"word": "Answer", "translation": "javob", "level": "A1", "example": "Write your answer on this paper."},
    {"word": "Area", "translation": "hudud, maydon", "level": "A2", "example": "This area is famous for its mountains."},
    {"word": "Arrival", "translation": "yetib kelish", "level": "A2", "example": "The arrival time of the train is 5 PM."},
    {"word": "Art", "translation": "san'at", "level": "A1", "example": "She loves modern art and painting."},
    {"word": "Autumn", "translation": "kuz", "level": "A1", "example": "The leaves turn yellow in autumn."},
    {"word": "Bad", "translation": "yomon", "level": "A1", "example": "Eating too much sugar is bad for your teeth."},
    {"word": "Ball", "translation": "koptok", "level": "A1", "example": "The boys are playing with a football."},
    {"word": "Bank", "translation": "bank", "level": "A1", "example": "I need to go to the bank to change money."},
    {"word": "Beach", "translation": "plyaj, sohil", "level": "A1", "example": "We spent the whole day on the beach."},
    {"word": "Bed", "translation": "karovat", "level": "A1", "example": "It is time to go to bed now."},
    {"word": "Bicycle", "translation": "velosiped", "level": "A1", "example": "He rides his bicycle to work every day."},
    {"word": "Bird", "translation": "qush", "level": "A1", "example": "A small blue bird is singing outside."},
    {"word": "Black", "translation": "qora", "level": "A1", "example": "She wore a elegant black dress."},
    {"word": "Blue", "translation": "ko'k", "level": "A1", "example": "The ocean is beautiful and blue."},
    {"word": "Boat", "translation": "qayiq", "level": "A1", "example": "We rented a small boat on the lake."},
    {"word": "Body", "translation": "tana", "level": "A1", "example": "Regular exercise is good for your body."},
    {"word": "Boring", "translation": "zerikarli", "level": "A1", "example": "The movie was so boring that I fell asleep."},
    {"word": "Box", "translation": "quti", "level": "A1", "example": "What is inside that big cardboard box?"},
    {"word": "Bridge", "translation": "ko'prik", "level": "A2", "example": "They are building a new bridge over the river."},
    {"word": "Building", "translation": "bino", "level": "A1", "example": "The Burj Khalifa is a very tall building."},
    {"word": "Bus", "translation": "avtobus", "level": "A1", "example": "I catch the bus at 8 AM every morning."},
    {"word": "Butter", "translation": "sariyog'", "level": "A1", "example": "Put some butter on your bread."},
    {"word": "Buy", "translation": "sotib olmoq", "level": "A1", "example": "I want to buy some fresh vegetables."},
    {"word": "Cake", "translation": "tort, pirog", "level": "A1", "example": "She baked a delicious chocolate cake."},
    {"word": "Camera", "translation": "fotoapparat", "level": "A1", "example": "Don't forget to bring your camera."},
    {"word": "Capital", "translation": "poytaxt", "level": "A2", "example": "London is the capital of the UK."},
    {"word": "Careful", "translation": "ehtiyotkor", "level": "A2", "example": "Be careful when you cross the street."},
    {"word": "Cheese", "translation": "pishloq", "level": "A1", "example": "I like to put cheese on my pizza."},
    {"word": "Chicken", "translation": "tovuq", "level": "A1", "example": "We had grilled chicken for dinner."},
    {"word": "Church", "translation": "klsa", "level": "A2", "example": "There is an old church near the square."},
    {"word": "Cinema", "translation": "kinoteatr", "level": "A1", "example": "Let's go to the cinema tonight."},
    {"word": "Class", "translation": "sinf, dars", "level": "A1", "example": "Our history class starts at nine."},
    {"word": "Clean", "translation": "toza", "level": "A1", "example": "You must keep your room clean."},
    {"word": "Clever", "translation": "aqlli", "level": "A2", "example": "He is a clever boy who understands quickly."},
    {"word": "Clock", "translation": "soat (devoriy)", "level": "A1", "example": "The clock on the wall says 10 PM."},
    {"word": "Close", "translation": "yopmoq / yaqin", "level": "A1", "example": "Please close the window."},
    {"word": "Clothes", "translation": "kiym-kechak", "level": "A1", "example": "He bought some new clothes for winter."},
    {"word": "Cloud", "translation": "bulut", "level": "A2", "example": "There isn't a single cloud in the sky."},
    {"word": "Coat", "translation": "palto, kurtka", "level": "A1", "example": "Put on your coat, it is freezing outside."},
    {"word": "Coffee", "translation": "kofe", "level": "A1", "example": "I prefer coffee with milk and sugar."},
    {"word": "Company", "translation": "kompaniya, korxona", "level": "A2", "example": "She works for a software company."},
    {"word": "Computer", "translation": "kompyuter", "level": "A1", "example": "I use my computer for coding and study."},
    {"word": "Cook", "translation": "pishirmoq", "level": "A1", "example": "My brother loves to cook Italian meals."},
    {"word": "Country", "translation": "davlat, mamlakat", "level": "A1", "example": "Uzbekistan is a beautiful country."},
    {"word": "Cow", "translation": "siyir", "level": "A1", "example": "The cow gives us milk every day."},
    {"word": "Cry", "translation": "yig'lamoq", "level": "A1", "example": "The baby started to cry for food."},
    {"word": "Cup", "translation": "finjon, krujka", "level": "A1", "example": "Would you like a cup of tea?"},
    {"word": "Dance", "translation": "raqsga tushmoq", "level": "A1", "example": "They like to dance at weddings."},
    {"word": "Dangerous", "translation": "xavfli", "level": "A2", "example": "Driving too fast is very dangerous."},
    {"word": "Dark", "translation": "qorong'u", "level": "A1", "example": "It gets dark very early in winter."},
    {"word": "Dear", "translation": "aziz, qadrli", "level": "A1", "example": "Thank you, my dear friend."},
    {"word": "Desk", "translation": "parta, yozuv stoli", "level": "A1", "example": "The student sat at his desk to write."},
    {"word": "Dictionary", "translation": "lug'at", "level": "A1", "example": "Look up the word in the dictionary."},
    {"word": "Dirty", "translation": "kir, iflos", "level": "A1", "example": "Wash your hands, they are dirty."},
    {"word": "Difficult", "translation": "qiyin", "level": "A1", "example": "This puzzle is too difficult for me."},
    {"word": "Drive", "translation": "haydamoq", "level": "A1", "example": "Can you drive a manual car?"},
    {"word": "Duck", "translation": "o'rdak", "level": "A1", "example": "The duck is swimming in the pond."},
    {"word": "Ear", "translation": "quloq", "level": "A1", "example": "We hear sounds with our ears."},
    {"word": "Earth", "translation": "Yer sayyorasi", "level": "A2", "example": "The Earth moves around the sun."},
    {"word": "East", "translation": "sharq", "level": "A2", "example": "The sun rises in the east."},
    {"word": "Egg", "translation": "tuxum", "level": "A1", "example": "I boiled an egg for breakfast."},
    {"word": "Eight", "translation": "sakkiz", "level": "A1", "example": "The class ends at eight o'clock."},
    {"word": "Elephant", "translation": "fil", "level": "A1", "example": "The elephant is the largest land animal."},
    {"word": "Empty", "translation": "bo'sh", "level": "A2", "example": "The bottle is empty, please refill it."},
    {"word": "Engine", "translation": "motor, dvigatel", "level": "A2", "example": "The car engine makes a strange noise."},
    {"word": "Engineer", "translation": "muhandis", "level": "A2", "example": "My cousin is a mechanical engineer."},
    {"word": "Enjoy", "translation": "huzurlanmoq, yoqtirmoq", "level": "A1", "example": "I really enjoy reading books."},
    {"word": "Evening", "translation": "oqshom, kechqurun", "level": "A1", "example": "We watch TV together in the evening."},
    {"word": "Every", "translation": "har bir", "level": "A1", "example": "Every student must attend the lecture."},
    {"word": "Exam", "translation": "imtihon", "level": "A1", "example": "She passed her driving exam easily."},
    {"word": "Exciting", "translation": "hayajonli, qiziqarli", "level": "A1", "example": "Football matches are always exciting."},
    {"word": "Expensive", "translation": "qimmat", "level": "A1", "example": "Gold jewelry is very expensive."},
    {"word": "Eye", "translation": "ko'z", "level": "A1", "example": "She has beautiful green eyes."},
    {"word": "Face", "translation": "yuz", "level": "A1", "example": "Wash your face with cold water."},
    {"word": "Factory", "translation": "zavod, fabrika", "level": "A2", "example": "He works at a car factory."},
    {"word": "Fall", "translation": "yiqilmoq / kuz", "level": "A1", "example": "Be Thesis, don't fall off the ladder."},
    {"word": "Famous", "translation": "mashhur", "level": "A1", "example": "He is a famous actor around the world."},
    {"word": "Farm", "translation": "ferma", "level": "A1", "example": "They grow tomatoes on their farm."},
    {"word": "Fast", "translation": "tez", "level": "A1", "example": "Cheetahs are very fast runners."},
    {"word": "Fat", "translation": "semiz", "level": "A1", "example": "The cat became fat because it ate too much."},
    {"word": "Find", "translation": "topmoq", "level": "A1", "example": "Did you find your missing keys?"},
    {"word": "Finger", "translation": "barmoq", "level": "A1", "example": "He cut his finger while cooking."},
    {"word": "Fire", "translation": "olov, yong'in", "level": "A1", "example": "We sat around the warm campfire."},
    {"word": "First", "translation": "birinchi", "level": "A1", "example": "January is the first month of the year."},
    {"word": "Flower", "translation": "gul", "level": "A1", "example": "Rose is my favorite flower."},
    {"word": "Fly", "translation": "uchmoq", "level": "A1", "example": "Birds can fly high in the sky."},
    {"word": "Forest", "translation": "o'rmon", "level": "A2", "example": "There are wolves in the deep forest."},
    {"word": "Forget", "translation": "unutmoq", "level": "A1", "example": "Don't forget to lock the main door."},
    {"word": "Fork", "translation": "vilka", "level": "A1", "example": "Eat your salad with a fork."},
    {"word": "Fruit", "translation": "meva", "level": "A1", "example": "Banana is a healthy fruit."},
    {"word": "Full", "translation": "to'la", "level": "A1", "example": "The glass is full of apple juice."},
    {"word": "Game", "translation": "o'yin", "level": "A1", "example": "Chess is a game of strategy."},
    {"word": "Glass", "translation": "stakan / shisha", "level": "A1", "example": "Can I have a glass of lemonade?"},
    {"word": "Gold", "translation": "oltin", "level": "A2", "example": "She received a gold medal for her win."},
    {"word": "Grass", "translation": "o't, maysa", "level": "A1", "example": "The grass is wet because of the rain."},
    {"word": "Green", "translation": "yashil", "level": "A1", "example": "Trees look green and beautiful in spring."},
    {"word": "Ground", "translation": "yer, zamin", "level": "A2", "example": "The apple fell to the ground."},
    {"word": "Group", "translation": "guruh", "level": "A1", "example": "A group of students visited the museum."},
    {"word": "Grow", "translation": "o'smoq, yetishtirmoq", "level": "A2", "example": "Plants need water and sunlight to grow."},
    {"word": "Hair", "translation": "soch", "level": "A1", "example": "She has long and curly hair."},
    {"word": "Half", "translation": "yarim", "level": "A2", "example": "Cut the orange in half, please."},
    {"word": "Hand", "translation": "qo'l", "level": "A1", "example": "Raise your hand if you know the answer."},
    {"word": "Hat", "translation": "shlyapa, bosh kiyim", "level": "A1", "example": "He wore a black hat yesterday."},
    {"word": "Head", "translation": "bosh", "level": "A1", "example": "My head hurts from the loud music."},
    {"word": "Healthy", "translation": "sog'lom", "level": "A2", "example": "Eating apples is a healthy choice."},
    {"word": "Hear", "translation": "eshitmoq", "level": "A1", "example": "Did you hear that loud noise?"},
    {"word": "Heavy", "translation": "og'ir", "level": "A1", "example": "This suitcase is too heavy to lift."},
    {"word": "High", "translation": "baland", "level": "A1", "example": "Mount Everest is a very high mountain."},
    {"word": "History", "translation": "tarix", "level": "A2", "example": "I love learning about ancient history."},
    {"word": "Hobby", "translation": "sevimli mashg'ulot", "level": "A1", "example": "My hobby is collecting rare stamps."},
    {"word": "Holiday", "translation": "ta'til, bayram", "level": "A1", "example": "We are planning a holiday in Spain."},
    {"word": "Horse", "translation": "ot (hayvon)", "level": "A1", "example": "He learned to ride a horse on the farm."},
    {"word": "Hospital", "translation": "shifoxona", "level": "A1", "example": "The ambulance took him to the hospital."},
    {"word": "Hotel", "translation": "mehmonxona", "level": "A1", "example": "We stayed in a 5-star hotel by the beach."},
    {"word": "Hour", "translation": "soat (vaqt birligi)", "level": "A1", "example": "The meeting lasted for one hour."},
    {"word": "Hungry", "translation": "och qolgan", "level": "A1", "example": "I am so hungry, let's cook something."},
    {"word": "Ice", "translation": "muz", "level": "A1", "example": "Put some ice cubes in my water, please."},
    {"word": "Idea", "translation": "goya, fikr", "level": "A1", "example": "That is an excellent idea!"},
    {"word": "Important", "translation": "muhim", "level": "A1", "example": "Learning English is important for my future."},
    {"word": "Island", "translation": "orol", "level": "A2", "example": "They went to a tropical island for vacation."},
    {"word": "Juice", "translation": "sharbat", "level": "A1", "example": "Orange juice is rich in Vitamin C."},
    {"word": "Key", "translation": "kalit", "level": "A1", "example": "I lost the key to my office room."},
    {"word": "Kind", "translation": "mehribon / tur, xil", "level": "A1", "example": "Thank you for your kind words."},
    {"word": "Kitchen", "translation": "oshxona", "level": "A1", "example": "My mother is baking a pie in the kitchen."},
    {"word": "Knee", "translation": "tizza", "level": "A2", "example": "He hurt his knee while playing basketball."},
    {"word": "Knife", "translation": "pichoq", "level": "A1", "example": "Be careful, that knife is sharp."},
    {"word": "Learn", "translation": "o'rganmoq", "level": "A1", "example": "I want to learn how to play guitar."},
    {"word": "Left", "translation": "chap tomondagi", "level": "A1", "example": "Turn left at the next traffic lights."},
    {"word": "Lesson", "translation": "dars, mashg'ulot", "level": "A1", "example": "Today's English lesson was fun."},
    {"word": "Library", "translation": "kutubxona", "level": "A1", "example": "I borrow books from the university library."},
    {"word": "Light", "translation": "yorug'lik / yengil", "level": "A1", "example": "Turn on the light, please."},
    {"word": "Listen", "translation": "tinglamoq", "level": "A1", "example": "I like to listen to classical music."},
    {"word": "Long", "translation": "uzun", "level": "A1", "example": "The Amazon is a very long river."},
    {"word": "Lunch", "translation": "tushlik", "level": "A1", "example": "What did you pack for lunch today?"},
    {"word": "Map", "translation": "xarita", "level": "A1", "example": "We used a tourist map to find the museum."},
    {"word": "Market", "translation": "bozor, market", "level": "A1", "example": "I buy fresh fruit at the local market."},
    {"word": "Match", "translation": "gugurt / o'yin", "level": "A1", "example": "Did you watch the football match?"},
    {"word": "Meal", "translation": "taom, ovqat", "level": "A2", "example": "Breakfast is the most important meal of the day."},
    {"word": "Meat", "translation": "go'sht", "level": "A1", "example": "I don't eat meat, I prefer fish."},
    {"word": "Meeting", "translation": "uchrashuv, majlis", "level": "A2", "example": "The manager called a short meeting."},
    {"word": "Money", "translation": "pul", "level": "A1", "example": "Save your money for useful things."},
    {"word": "Month", "translation": "oy (vaqt)", "level": "A1", "example": "We are going on holiday next month."},
    {"word": "Moon", "translation": "Oy (yo'ldosh)", "level": "A1", "example": "The moon looks very beautiful tonight."},
    {"word": "Mountain", "translation": "tog'", "level": "A1", "example": "They climbed the highest mountain last summer."},
    {"word": "Mouth", "translation": "og'iz", "level": "A1", "example": "Open your mouth and say 'Ah'."},
    {"word": "Museum", "translation": "muzey", "level": "A1", "example": "The city museum has ancient coins."},
    {"word": "Music", "translation": "musika", "level": "A1", "example": "She listens to pop music every day."},
    {"word": "Name", "translation": "ism, nom", "level": "A1", "example": "What is your teacher's name?"},
    # --- YANGI QO'SHILGAN JAMI 150 TA SO'Z (300 TALIK RO'YXAT) ---
    {"word": "About", "translation": "haqida", "level": "A1", "example": "Tell me about your family."},
    {"word": "Address", "translation": "manzil", "level": "A1", "example": "What is your home address?"},
    {"word": "Adult", "translation": "katta yoshli odam", "level": "A1", "example": "This movie is for adults only."},
    {"word": "Afternoon", "translation": "tushdan keyin", "level": "A1", "example": "I will see you this afternoon."},
    {"word": "Age", "translation": "yosh", "level": "A1", "example": "He passed away at an early age."},
    {"word": "All", "translation": "barcha, hamma", "level": "A1", "example": "All the students passed the test."},
    {"word": "Angry", "translation": "jahli chiqqan", "level": "A1", "example": "Why are you so angry with me?"},
    {"word": "Another", "translation": "boshqa bitta", "level": "A1", "example": "Would you like another cup of tea?"},
    {"word": "Apartment", "translation": "kvartira", "level": "A1", "example": "They live in a small apartment."},
    {"word": "Ask", "translation": "so'ramoq", "level": "A1", "example": "Can I ask you a simple question?"},
    {"word": "Baby", "translation": "chaqaloq", "level": "A1", "example": "The baby is sleeping in the bed."},
    {"word": "Back", "translation": "orqa, orqaga", "level": "A1", "example": "Go back to your place, please."},
    {"word": "Bag", "translation": "sumka", "level": "A1", "example": "Put your books in your school bag."},
    {"word": "Bath", "translation": "vanna, cho'milish", "level": "A1", "example": "I usually take a hot bath at night."},
    {"word": "Bathroom", "translation": "yuvinish xonasi", "level": "A1", "example": "Where is the nearest bathroom?"},
    {"word": "Before", "translation": "oldin, ilgari", "level": "A1", "example": "Wash your hands before eating dinner."},
    {"word": "Begin", "translation": "boshlamoq", "level": "A1", "example": "The English lesson will begin now."},
    {"word": "Behind", "translation": "orqasida", "level": "A1", "example": "The cat hiding behind the door."},
    {"word": "Below", "translation": "pastda, quyida", "level": "A1", "example": "Read the sentences below carefully."},
    {"word": "Between", "translation": "o'rtasida", "level": "A1", "example": "The table is between the two chairs."},
    {"word": "Birthday", "translation": "tug'ilgan kun", "level": "A1", "example": "Tomorrow is my mother's birthday."},
    {"word": "Boat", "translation": "qayiq", "level": "A1", "example": "We went fishing in a small boat."},
    {"word": "Bored", "translation": "zerikkan", "level": "A1", "example": "I am bored, let's watch a movie."},
    {"word": "Born", "translation": "tug'ilgan", "level": "A1", "example": "I was born in a small village."},
    {"word": "Both", "translation": "ikkala, ikkisi ham", "level": "A1", "example": "Both brothers play football very well."},
    {"word": "Bottle", "translation": "shisha, butilka", "level": "A1", "example": "Bring a cold bottle of water."},
    {"word": "Bottom", "translation": "pastki qism, tagi", "level": "A1", "example": "The keys are at the bottom of the bag."},
    {"word": "Bring", "translation": "olib kelmoq", "level": "A1", "example": "Please bring me the dictionary."},
    {"word": "Business", "translation": "biznes, tadbirkorlik", "level": "A1", "example": "He runs a successful software business."},
    {"word": "Call", "translation": "qo'ng'iroq qilmoq", "level": "A1", "example": "Please call me back this evening."},
    {"word": "Can", "translation": "bajara olmoq", "level": "A1", "example": "I can speak three languages fluently."},
    {"word": "Card", "translation": "karta, otkritka", "level": "A1", "example": "Write your name on this flashcard."},
    {"word": "Carry", "translation": "ko'tarib yurmoq", "level": "A1", "example": "Let me help you carry that bag."},
    {"word": "Case", "translation": "holat, quti, g'ilof", "level": "A1", "example": "In this case, we need professional help."},
    {"word": "Catch", "translation": "tutmoq, ulgurmoq", "level": "A1", "example": "Run fast to catch the early bus."},
    {"word": "Center", "translation": "markaz", "level": "A1", "example": "We walked around the city center."},
    {"word": "Century", "translation": "asr, yuz yillik", "level": "A1", "example": "We live in the twenty-first century."},
    {"word": "Change", "translation": "o'zgartirmoq, mayda pul", "level": "A1", "example": "You need to change your bad habits."},
    {"word": "Chat", "translation": "suhbatlashmoq", "level": "A1", "example": "I love to chat with Jo'rabek AI."},
    {"word": "Cheap", "translation": "arzon", "level": "A1", "example": "This phone is very cheap but good."},
    {"word": "Check", "translation": "tekshirmoq", "level": "A1", "example": "Please check your answers once again."},
    {"word": "Classmate", "translation": "sinfdosh", "level": "A1", "example": "Shohjahon is my favorite classmate."},
    {"word": "Clean", "translation": "toza, tozalamoq", "level": "A1", "example": "You must keep your room clean."},
    {"word": "Climb", "translation": "tirmashib chiqmoq", "level": "A1", "example": "Don't climb that tall old tree."},
    {"word": "College", "translation": "kollej, oliygoh", "level": "A1", "example": "She studies English literature at college."},
    {"word": "Color", "translation": "rang", "level": "A1", "example": "Green is the main color of Studex."},
    {"word": "Come", "translation": "kelmoq", "level": "A1", "example": "Please come to my birthday party."},
    {"word": "Conversation", "translation": "suhbat", "level": "A1", "example": "We had a long conversation about IELTS."},
    {"word": "Course", "translation": "kurs, o'quv kursi", "level": "A1", "example": "I am taking an advanced coding course."},
    {"word": "Cousin", "translation": "amakivachcha, xolavachcha", "level": "A1", "example": "My cousin is a professional engineer."},
    {"word": "Cross", "translation": "kesib o'tmoq", "level": "A1", "example": "Be careful when you cross the street."},
    {"word": "Desk", "translation": "parta, yozuv stoli", "level": "A1", "example": "Sit at your desk and start writing."},
    {"word": "Die", "translation": "vafot etmoq, o'lmoq", "level": "A1", "example": "Plants will die without any water."},
    {"word": "Difference", "translation": "farq", "level": "A1", "example": "What is the difference between them?"},
    {"word": "Different", "translation": "turli xil, boshqacha", "level": "A1", "example": "They have two very different ideas."},
    {"word": "Difficult", "translation": "qiyin, murakkab", "level": "A1", "example": "This math test is too difficult."},
    {"word": "Draw", "translation": "rasm chizmoq", "level": "A1", "example": "The child likes to draw blue birds."},
    {"word": "Dress", "translation": "ko'ylak (ayollar uchun)", "level": "A1", "example": "She wore a beautiful red dress."},
    {"word": "Drink", "translation": "ichmoq, ichimlik", "level": "A1", "example": "I always drink milk in the morning."},
    {"word": "Drive", "translation": "haydamoq", "level": "A1", "example": "My father learned to drive last year."},
    {"word": "Driver", "translation": "haydovchi", "level": "A1", "example": "The bus driver was very polite."},
    {"word": "During", "translation": "davomida, mobaynida", "level": "A1", "example": "Do not speak during the examination."},
    {"word": "Each", "translation": "har biri", "level": "A1", "example": "Each student received a new book."},
    {"word": "Early", "translation": "erta, barvaqt", "level": "A1", "example": "I usually wake up early in summer."},
    {"word": "East", "translation": "sharq", "level": "A1", "example": "The sun rises in the east every day."},
    {"word": "End", "translation": "tugallanish, oxiri", "level": "A1", "example": "This is the end of the first chapter."},
    {"word": "Engineer", "translation": "muhandis", "level": "A1", "example": "He wants to become a software engineer."},
    {"word": "Enough", "translation": "etarli, yetarli darajada", "level": "A1", "example": "We have enough food for dinner."},
    {"word": "Even", "translation": "hatto, hattoki", "level": "A1", "example": "He didn't even say goodbye to us."},
    {"word": "Ever", "translation": "hech, qachondir", "level": "A1", "example": "Have you ever been to Samarkand?"},
    {"word": "Everyone", "translation": "har bir kishi, hamma", "level": "A1", "example": "Everyone is ready for the IELTS exam."},
    {"word": "Everything", "translation": "hamma narsa", "level": "A1", "example": "Everything is completely clear now."},
    {"word": "Example", "translation": "misol", "level": "A1", "example": "Read the example before doing the task."},
    {"word": "Excellent", "translation": "ajoyib, a'lo", "level": "A1", "example": "Your English pronunciation is excellent."},
    {"word": "Exciting", "translation": "hayajonli", "level": "A1", "example": "The final football match was exciting."},
    {"word": "Exercise", "translation": "mashq, jismoniy tarbiya", "level": "A1", "example": "Morning exercise is good for health."},
    {"word": "Expensive", "translation": "qimmat, qimmatbaho", "level": "A1", "example": "This luxury car is very expensive."},
    {"word": "Explain", "translation": "tushuntirmoq", "level": "A1", "example": "Can you explain this rule again?"},
    {"word": "Fact", "translation": "fakt, haqiqat", "level": "A1", "example": "It is a fact that water freezes at 0 degrees."},
    {"word": "Fall", "translation": "yiqilmoq, pasaymoq", "level": "A1", "example": "Be careful, don't fall off the stairs."},
    {"word": "Far", "translation": "uzoqlikda, uzoq", "level": "A1", "example": "The train station is very far from here."},
    {"word": "Fast", "translation": "tezkor, tez", "level": "A1", "example": "He is a very fast runner."},
    {"word": "Feel", "translation": "his qilmoq", "level": "A1", "example": "I feel very happy today."},
    {"word": "Festival", "translation": "festival, bayram", "level": "A1", "example": "Navruz is a famous traditional festival."},
    {"word": "Few", "translation": "kam, bir nechta", "level": "A1", "example": "There are a few apples in the box."},
    {"word": "Film", "translation": "film, kino", "level": "A1", "example": "We watched an interesting documentary film."},
    {"word": "Find", "translation": "topmoq", "level": "A1", "example": "Did you find your missing keys?"},
    {"word": "Finish", "translation": "tugatmoq", "level": "A1", "example": "I need to finish my homework tonight."},
    {"word": "First", "translation": "birinchi", "level": "A1", "example": "This is my first time using Studex."},
    {"word": "Fly", "translation": "uchmoq, pashsha", "level": "A1", "example": "Birds can fly high in the sky."},
    {"word": "Follow", "translation": "ergashmoq, amal qilmoq", "level": "A1", "example": "Please follow the rules of the app."},
    {"word": "Foreign", "translation": "xorijiy, chet el", "level": "A1", "example": "Learning a foreign language takes time."},
    {"word": "Forest", "translation": "o'rmon", "level": "A1", "example": "They went for a walk in the forest."},
    {"word": "Forget", "translation": "unutmoq", "level": "A1", "example": "Don't forget to review the words."},
    {"word": "Free", "translation": "bepul, bo'sh", "level": "A1", "example": "Jo'rabek AI is a completely free tool."},
    {"word": "Future", "translation": "kelajak", "level": "A1", "example": "Studex will help your future career."},
    {"word": "Give", "translation": "bermoq", "level": "A1", "example": "Give me a piece of paper, please."},
    {"word": "Glass", "translation": "stakan, shisha", "level": "A1", "example": "He broke the glass window by accident."},
    {"word": "Go", "translation": "bormoq", "level": "A1", "example": "Let's go to the school library."},
    {"word": "Great", "translation": "buyuk, ulug', ajoyib", "level": "A1", "example": "This is a great opportunity for us."},
    {"word": "Group", "translation": "guruh", "level": "A1", "example": "A group of people stood outside."},
    {"word": "Grow", "translation": "o'smoq, kattalashmoq", "level": "A1", "example": "Plants grow quickly in spring."},
    {"word": "Guess", "translation": "taxmin qilmoq", "level": "A1", "example": "Can you guess his real age?"},
    {"word": "Half", "translation": "yarim", "level": "A1", "example": "The lesson lasted for half an hour."},
    {"word": "Happen", "translation": "sodir bo'lmoq", "level": "A1", "example": "What will happen if we fail?"},
    {"word": "Hard", "translation": "qiyin, qattiq", "level": "A1", "example": "He works hard to pass IELTS."},
    {"word": "Healthy", "translation": "sog'lom", "level": "A1", "example": "Eating apples is a healthy habit."},
    {"word": "Hear", "translation": "eshitmoq", "level": "A1", "example": "I can't hear your voice clearly."},
    {"word": "Heavy", "translation": "og'ir", "level": "A1", "example": "This box is too heavy to lift."},
    {"word": "Help", "translation": "yordam bermoq, yordam", "level": "A1", "example": "Can you help me with this task?"},
    {"word": "High", "translation": "baland, yuqori", "level": "A1", "example": "The mountain is very high and dangerous."},
    {"word": "History", "translation": "tarix", "level": "A1", "example": "I find ancient history fascinating."},
    {"word": "Hobby", "translation": "sevimli mashg'ulot", "level": "A1", "example": "My favorite hobby is reading books."},
    {"word": "Hold", "translation": "ushlab turmoq", "level": "A1", "example": "Please hold the door for me."},
    {"word": "Hope", "translation": "umid qilmoq", "level": "A1", "example": "I hope you pass the test easily."},
    {"word": "Hospital", "translation": "shifoxona", "level": "A1", "example": "The sick man is in the hospital."},
    {"word": "Hotel", "translation": "mehmonxona", "level": "A1", "example": "We stayed at a modern hotel."},
    {"word": "Hour", "translation": "soat (vaqt birligi)", "level": "A1", "example": "We waited for an hour in the bus."},
    {"word": "How", "translation": "qanday, qanaqa", "level": "A1", "example": "How do you spell this English word?"},
    {"word": "Hundred", "translation": "yuz", "level": "A1", "example": "There are one hundred words here."},
    {"word": "Hungry", "translation": "och, qorini ochgan", "level": "A1", "example": "I am hungry, let's get some food."},
    {"word": "Idea", "translation": "g'oya, fikr", "level": "A1", "example": "That is an excellent business idea."},
    {"word": "Important", "translation": "muhim, ahamiyatli", "level": "A1", "example": "Vocabulary is very important for IELTS."},
    {"word": "Information", "translation": "ma'lumot", "level": "A1", "example": "Can you give me more information?"},
    {"word": "Inside", "translation": "ichkarida, ichida", "level": "A1", "example": "What is inside that small box?"},
    {"word": "Interest", "translation": "qiziqish", "level": "A1", "example": "He has a great interest in computers."},
    {"word": "Interesting", "translation": "qiziqarli", "level": "A1", "example": "This is an interesting Python project."},
    {"word": "Internet", "translation": "internet", "level": "A1", "example": "You need the internet to load AI."},
    {"word": "Interview", "translation": "intervyu, suhbat", "level": "A1", "example": "He passed the job interview successfully."},
    {"word": "Into", "translation": "ichiga", "level": "A1", "example": "Put the old files into the folder."},
    {"word": "Island", "translation": "orol", "level": "A1", "example": "They visited a beautiful tropical island."},
    {"word": "Journey", "translation": "sayohat", "level": "A1", "example": "Have a safe journey to London."},
    {"word": "Juice", "translation": "sharbat", "level": "A1", "example": "I prefer fresh orange juice."},
    {"word": "Keep", "translation": "saqlamoq, davom ettirmoq", "level": "A1", "example": "Please keep your room clean."},
    {"word": "Key", "translation": "kalit, kalit so'z", "level": "A1", "example": "Where is the key to the office?"},
    {"word": "Kind", "translation": "mehribon, tur, xil", "level": "A1", "example": "She is a very kind and helpful lady."},
    {"word": "Kitchen", "translation": "oshxona", "level": "A1", "example": "The food is being prepared in the kitchen."},
    {"word": "Knee", "translation": "tizza", "level": "A1", "example": "He hurt his knee while playing sports."},
    {"word": "Knife", "translation": "pichoq", "level": "A1", "example": "Be careful, that knife is very sharp."},
    {"word": "Know", "translation": "bilmoq", "level": "A1", "example": "Do you know the answer to this?"},
    {"word": "Land", "translation": "er, zamin, mamlakat", "level": "A1", "example": "The plane will land in ten minutes."},
    {"word": "Large", "translation": "katta, ulkan", "level": "A1", "example": "They live in a large house."},
    {"word": "Last", "translation": "oxirgi, o'tgan", "level": "A1", "example": "Last night I finished the code."},
    {"word": "Late", "translation": "kech, kechikkan", "level": "A1", "example": "Don't be late for the class."},
    {"word": "Laugh", "translation": "kulmoq", "level": "A1", "example": "His funny jokes made everyone laugh."},
    {"word": "Learn", "translation": "o'rganmoq", "level": "A1", "example": "I want to learn how to code."},
    {"word": "Leave", "translation": "tark etmoq, qoldirmoq", "level": "A1", "example": "Do not leave your bags here."},
    {"word": "Left", "translation": "chap, chap tomon", "level": "A1", "example": "Turn left at the next corner."},
    {"word": "Leg", "translation": "oyoq (tana a'zosi)", "level": "A1", "example": "He broke his leg playing football."},
    {"word": "Lesson", "translation": "dars", "level": "A1", "example": "Today's lesson was very useful."},
    {"word": "Letter", "translation": "xat, harf", "level": "A1", "example": "I received an official letter today."},
    {"word": "Library", "translation": "kutubxona", "level": "A1", "example": "The library is a quiet place."},
    {"word": "Lie", "translation": "yolg'on gapirmoq, yotmoq", "level": "A1", "example": "Never tell a lie to your friends."},
    {"word": "Light", "translation": "yorug'lik, yengil", "level": "A1", "example": "Turn on the light, it is dark."},
    {"word": "Like", "translation": "yoqtirmoq, o'xshash", "level": "A1", "example": "I like learning new languages."},
    {"word": "Line", "translation": "chiziq, qator", "level": "A1", "example": "Draw a straight line on the paper."},
    {"word": "Listen", "translation": "tinglamoq, quloq solmoq", "level": "A1", "example": "Listen to the audio recording carefully."}
]

# Kengaytirilgan B1-B2 (Intermediate) darajasidagi so'zlar bazasi
VOCAB_B1_B2 = [
    {"word": "Achieve", "translation": "erishmoq", "level": "B1", "example": "She achieved her goal after years of hard work."},
    {"word": "Advantage", "translation": "ustunlik, afzallik", "level": "B1", "example": "Living in the city has many advantages."},
    {"word": "Advertisement", "translation": "reklama", "level": "B1", "example": "The advertisement was shown on TV every day."},
    {"word": "Afford", "translation": "qurbi yetmoq", "level": "B1", "example": "I can't afford a new car this year."},
    {"word": "Ancient", "translation": "qadimiy", "level": "B1", "example": "The museum displays many ancient artifacts."},
    {"word": "Anxious", "translation": "xavotirli", "level": "B1", "example": "She felt anxious before the exam."},
    {"word": "Appreciate", "translation": "qadrlamoq", "level": "B1", "example": "I really appreciate your help."},
    {"word": "Approach", "translation": "yondashuv, yaqinlashmoq", "level": "B1", "example": "We need a new approach to this problem."},
    {"word": "Argument", "translation": "bahs, dalil", "level": "B1", "example": "They had an argument about money."},
    {"word": "Attitude", "translation": "munosabat", "level": "B1", "example": "His attitude towards work has changed."},
    {"word": "Available", "translation": "mavjud, bo'sh", "level": "B1", "example": "The manager is not available right now."},
    {"word": "Aware", "translation": "xabardor", "level": "B1", "example": "Are you aware of the new rules?"},
    {"word": "Behaviour", "translation": "xatti-harakat", "level": "B1", "example": "The teacher praised his good behaviour."},
    {"word": "Benefit", "translation": "foyda", "level": "B1", "example": "Exercise has many benefits for health."},
    {"word": "Career", "translation": "karyera", "level": "B1", "example": "She wants to build a career in medicine."},
    {"word": "Challenge", "translation": "qiyinchilik, sinov", "level": "B1", "example": "Learning a new language is a big challenge."},
    {"word": "Community", "translation": "jamiyat, mahalla", "level": "B1", "example": "The community worked together to clean the park."},
    {"word": "Compare", "translation": "solishtirmoq", "level": "B1", "example": "Compare the two products before buying."},
    {"word": "Competition", "translation": "raqobat", "level": "B1", "example": "There is strong competition in this market."},
    {"word": "Complain", "translation": "shikoyat qilmoq", "level": "B1", "example": "Customers complained about the service."},
    {"word": "Complex", "translation": "murakkab", "level": "B1", "example": "The instructions were too complex to follow."},
    {"word": "Concentrate", "translation": "diqqatni jamlamoq", "level": "B1", "example": "I can't concentrate with all this noise."},
    {"word": "Confident", "translation": "ishonchli", "level": "B1", "example": "She felt confident about the interview."},
    {"word": "Conflict", "translation": "ziddiyat", "level": "B1", "example": "The conflict between the two countries continued."},
    {"word": "Consequence", "translation": "oqibat", "level": "B1", "example": "Every action has a consequence."},
    {"word": "Consider", "translation": "hisobga olmoq", "level": "B1", "example": "We should consider all the options."},
    {"word": "Consume", "translation": "iste'mol qilmoq", "level": "B1", "example": "People consume more sugar than before."},
    {"word": "Contribute", "translation": "hissa qo'shmoq", "level": "B1", "example": "Everyone should contribute to the project."},
    {"word": "Convenient", "translation": "qulay", "level": "B1", "example": "This is a convenient location for the office."},
    {"word": "Cooperate", "translation": "hamkorlik qilmoq", "level": "B1", "example": "The two teams cooperated well."},
    {"word": "Culture", "translation": "madaniyat", "level": "B1", "example": "Uzbek culture is rich in traditions."},
    {"word": "Debate", "translation": "munozara", "level": "B1", "example": "There was a debate about climate change."},
    {"word": "Decade", "translation": "o'n yillik", "level": "B1", "example": "The city has changed a lot in the last decade."},
    {"word": "Demand", "translation": "talab", "level": "B1", "example": "There is high demand for skilled workers."},
    {"word": "Depend", "translation": "bog'liq bo'lmoq", "level": "B1", "example": "Success depends on hard work."},
    {"word": "Determine", "translation": "aniqlamoq", "level": "B1", "example": "The test will determine your level."},
    {"word": "Develop", "translation": "rivojlantirmoq", "level": "B1", "example": "The company wants to develop new products."},
    {"word": "Device", "translation": "qurilma", "level": "B1", "example": "This device helps you track your sleep."},
    {"word": "Diverse", "translation": "xilma-xil", "level": "B1", "example": "The city has a diverse population."},
    {"word": "Economy", "translation": "iqtisodiyot", "level": "B1", "example": "The economy grew rapidly last year."},
    {"word": "Efficient", "translation": "samarali", "level": "B1", "example": "We need a more efficient system."},
    {"word": "Emphasize", "translation": "ta'kidlamoq", "level": "B1", "example": "The teacher emphasized the importance of practice."},
    {"word": "Enable", "translation": "imkon bermoq", "level": "B1", "example": "Technology enables us to work from home."},
    {"word": "Encourage", "translation": "rag'batlantirmoq", "level": "B1", "example": "Parents should encourage their children to read."},
    {"word": "Environment", "translation": "atrof-muhit", "level": "B1", "example": "We must protect the environment."},
    {"word": "Establish", "translation": "tashkil etmoq", "level": "B1", "example": "The company was established in 1990."},
    {"word": "Estimate", "translation": "taxmin qilmoq", "level": "B1", "example": "Experts estimate the cost will rise."},
    {"word": "Ethical", "translation": "axloqiy", "level": "B1", "example": "The company follows ethical business practices."},
    {"word": "Evidence", "translation": "dalil", "level": "B1", "example": "There is no evidence to support this claim."},
    {"word": "Evolve", "translation": "rivojlanmoq", "level": "B1", "example": "Technology continues to evolve quickly."},
    {"word": "Exaggerate", "translation": "bo'rttirmoq", "level": "B1", "example": "Don't exaggerate the problem."},
    {"word": "Examine", "translation": "tekshirmoq", "level": "B1", "example": "The doctor examined the patient carefully."},
    {"word": "Exceed", "translation": "oshib ketmoq", "level": "B1", "example": "The results exceeded our expectations."},
    {"word": "Expand", "translation": "kengaymoq", "level": "B1", "example": "The business plans to expand overseas."},
    {"word": "Expose", "translation": "ta'sir qilmoq, fosh qilmoq", "level": "B1", "example": "Children should be exposed to books early."},
    {"word": "Factor", "translation": "omil", "level": "B1", "example": "Diet is an important factor in health."},
    {"word": "Flexible", "translation": "moslashuvchan", "level": "B1", "example": "Our schedule is flexible this week."},
    {"word": "Focus", "translation": "e'tibor qaratmoq", "level": "B1", "example": "Let's focus on the main issue."},
    {"word": "Frustrated", "translation": "asabiylashgan", "level": "B1", "example": "He felt frustrated with the slow internet."},
    {"word": "Function", "translation": "vazifa, ishlamoq", "level": "B1", "example": "This app has many useful functions."},
    {"word": "Generation", "translation": "avlod", "level": "B1", "example": "The younger generation uses more technology."},
    {"word": "Genuine", "translation": "haqiqiy", "level": "B1", "example": "She has a genuine interest in art."},
    {"word": "Global", "translation": "global", "level": "B1", "example": "Global warming is a serious issue."},
    {"word": "Goal", "translation": "maqsad", "level": "B1", "example": "My goal is to improve my English."},
    {"word": "Government", "translation": "hukumat", "level": "B1", "example": "The government introduced new laws."},
    {"word": "Gradually", "translation": "asta-sekin", "level": "B1", "example": "The weather gradually improved."},
    {"word": "Guarantee", "translation": "kafolat", "level": "B1", "example": "The product comes with a two-year guarantee."},
    {"word": "Habit", "translation": "odat", "level": "B1", "example": "Reading before bed is a good habit."},
    {"word": "Identify", "translation": "aniqlamoq", "level": "B1", "example": "Doctors identified the cause of the illness."},
    {"word": "Illustrate", "translation": "tasvirlamoq", "level": "B1", "example": "The graph illustrates the growth in sales."},
    {"word": "Impact", "translation": "ta'sir", "level": "B1", "example": "Social media has a big impact on society."},
    {"word": "Implement", "translation": "amalga oshirmoq", "level": "B1", "example": "The school will implement a new policy."},
    {"word": "Improve", "translation": "yaxshilamoq", "level": "B1", "example": "She wants to improve her writing skills."},
    {"word": "Include", "translation": "o'z ichiga olmoq", "level": "B1", "example": "The price includes breakfast."},
    {"word": "Increase", "translation": "oshirmoq, ko'paymoq", "level": "B1", "example": "Prices increased last month."},
    {"word": "Independent", "translation": "mustaqil", "level": "B1", "example": "She became independent after university."},
    {"word": "Individual", "translation": "shaxs, individual", "level": "B1", "example": "Each individual has unique needs."},
    {"word": "Influence", "translation": "ta'sir qilmoq", "level": "B1", "example": "Parents influence their children's behaviour."},
    {"word": "Innovative", "translation": "innovatsion", "level": "B1", "example": "The company is known for innovative ideas."},
    {"word": "Insist", "translation": "qat'iy talab qilmoq", "level": "B1", "example": "He insisted on paying the bill."},
    {"word": "Instead", "translation": "o'rniga", "level": "B1", "example": "Let's walk instead of driving."},
    {"word": "Institution", "translation": "muassasa", "level": "B1", "example": "The university is a respected institution."},
    {"word": "Interact", "translation": "muloqot qilmoq", "level": "B1", "example": "Children learn by interacting with others."},
    {"word": "Interpret", "translation": "talqin qilmoq", "level": "B1", "example": "It's hard to interpret his behaviour."},
    {"word": "Involve", "translation": "jalb qilmoq", "level": "B1", "example": "The project involves many departments."},
    {"word": "Issue", "translation": "masala", "level": "B1", "example": "Pollution is a major issue in cities."},
    {"word": "Justify", "translation": "oqlamoq, asoslamoq", "level": "B1", "example": "Can you justify this decision?"},
    {"word": "Labour", "translation": "mehnat", "level": "B1", "example": "Labour costs have increased this year."},
    {"word": "Legal", "translation": "huquqiy", "level": "B1", "example": "It is not legal to drive without a licence."},
    {"word": "Maintain", "translation": "saqlab qolmoq", "level": "B1", "example": "It's important to maintain good health."},
    {"word": "Major", "translation": "asosiy, katta", "level": "B1", "example": "Education is a major factor in success."},
    {"word": "Manage", "translation": "boshqarmoq", "level": "B1", "example": "She manages a small team at work."},
    {"word": "Method", "translation": "usul", "level": "B1", "example": "This method is very effective for learning."},
    {"word": "Modify", "translation": "o'zgartirmoq", "level": "B1", "example": "We need to modify our plan slightly."},
    {"word": "Motivate", "translation": "rag'batlantirmoq", "level": "B1", "example": "Good teachers motivate their students."},
    {"word": "Negative", "translation": "salbiy", "level": "B1", "example": "Stress can have a negative effect on health."},
    {"word": "Objective", "translation": "maqsad, xolis", "level": "B1", "example": "Our main objective is to reduce costs."},
    {"word": "Obtain", "translation": "olmoq, erishmoq", "level": "B1", "example": "She obtained a degree in economics."},
    {"word": "Occupy", "translation": "egallamoq", "level": "B1", "example": "The building is occupied by several companies."},
    {"word": "Opportunity", "translation": "imkoniyat", "level": "B1", "example": "This job is a great opportunity for her."},
    {"word": "Overcome", "translation": "yengib o'tmoq", "level": "B1", "example": "He overcame many difficulties in life."},
    {"word": "Participate", "translation": "ishtirok etmoq", "level": "B1", "example": "Students participated in the competition."},
    {"word": "Permanent", "translation": "doimiy", "level": "B1", "example": "She found a permanent job in the city."},
    {"word": "Perspective", "translation": "nuqtai nazar", "level": "B1", "example": "Try to see it from another perspective."},
    {"word": "Positive", "translation": "ijobiy", "level": "B1", "example": "He has a positive attitude to life."},
    {"word": "Potential", "translation": "salohiyat, imkoniyat", "level": "B1", "example": "The student has great potential."},
    {"word": "Practical", "translation": "amaliy", "level": "B1", "example": "We need a practical solution to this."},
    {"word": "Predict", "translation": "bashorat qilmoq", "level": "B1", "example": "It's hard to predict the weather."},
    {"word": "Prefer", "translation": "afzal ko'rmoq", "level": "B1", "example": "I prefer tea to coffee."},
    {"word": "Previous", "translation": "oldingi", "level": "B1", "example": "The previous manager left last month."},
    {"word": "Primary", "translation": "asosiy, boshlang'ich", "level": "B1", "example": "Education is the primary goal here."},
    {"word": "Priority", "translation": "ustuvorlik", "level": "B1", "example": "Health should be your top priority."},
    {"word": "Process", "translation": "jarayon", "level": "B1", "example": "Learning a language is a slow process."},
    {"word": "Promote", "translation": "ilgari surmoq, reklama qilmoq", "level": "B1", "example": "The government promotes healthy eating."},
    {"word": "Proportion", "translation": "nisbat", "level": "B1", "example": "A large proportion of students passed."},
    {"word": "Purpose", "translation": "maqsad", "level": "B1", "example": "What is the purpose of this meeting?"},
    {"word": "Pursue", "translation": "intilmoq, davom ettirmoq", "level": "B1", "example": "She decided to pursue a career in law."},
    {"word": "Rapid", "translation": "tez", "level": "B1", "example": "The city has seen rapid growth."},
    {"word": "Rare", "translation": "kamdan-kam", "level": "B1", "example": "It's rare to see snow here in winter."},
    {"word": "React", "translation": "reaksiya bildirmoq", "level": "B1", "example": "How did she react to the news?"},
    {"word": "Recognize", "translation": "tan olmoq, tanimoq", "level": "B1", "example": "I didn't recognize him at first."},
    {"word": "Recommend", "translation": "tavsiya qilmoq", "level": "B1", "example": "I recommend this book to everyone."},
    {"word": "Reduce", "translation": "kamaytirmoq", "level": "B1", "example": "We should reduce our use of plastic."},
    {"word": "Reflect", "translation": "aks ettirmoq, fikr yuritmoq", "level": "B1", "example": "Take time to reflect on your choices."},
    {"word": "Regard", "translation": "hisoblamoq, nuqtai nazar", "level": "B1", "example": "Many regard him as an expert."},
    {"word": "Reject", "translation": "rad etmoq", "level": "B1", "example": "The committee rejected the proposal."},
    {"word": "Reliable", "translation": "ishonchli", "level": "B1", "example": "She is a reliable and hardworking employee."},
    {"word": "Rely", "translation": "ishonmoq, tayanmoq", "level": "B1", "example": "You can rely on him in difficult times."},
    {"word": "Represent", "translation": "vakillik qilmoq", "level": "B1", "example": "This graph represents last year's sales."},
    {"word": "Require", "translation": "talab qilmoq", "level": "B1", "example": "The job requires good communication skills."},
    {"word": "Resource", "translation": "resurs", "level": "B1", "example": "Water is a valuable natural resource."},
    {"word": "Respond", "translation": "javob bermoq", "level": "B1", "example": "She responded quickly to the email."},
    {"word": "Restrict", "translation": "cheklamoq", "level": "B1", "example": "The new law restricts smoking in public places."},
    {"word": "Reveal", "translation": "oshkor qilmoq", "level": "B1", "example": "The survey revealed interesting results."},
    {"word": "Role", "translation": "rol", "level": "B1", "example": "Teachers play an important role in society."},
    {"word": "Routine", "translation": "kundalik tartib", "level": "B1", "example": "Exercise is part of my daily routine."},
    {"word": "Rural", "translation": "qishloq", "level": "B1", "example": "Many people are moving from rural areas to cities."},
    {"word": "Satisfy", "translation": "qanoatlantirmoq", "level": "B1", "example": "The meal satisfied everyone at the table."},
    {"word": "Secure", "translation": "xavfsiz, ta'minlamoq", "level": "B1", "example": "She wants a secure job with good pay."},
    {"word": "Significant", "translation": "muhim, sezilarli", "level": "B1", "example": "There was a significant increase in sales."},
    {"word": "Similar", "translation": "o'xshash", "level": "B1", "example": "These two cars are quite similar."},
    {"word": "Solution", "translation": "yechim", "level": "B1", "example": "We need to find a solution to this problem."},
    {"word": "Source", "translation": "manba", "level": "B1", "example": "The internet is a good source of information."},
    {"word": "Specific", "translation": "aniq, muayyan", "level": "B1", "example": "Please give a specific example."},
    {"word": "Stable", "translation": "barqaror", "level": "B1", "example": "The country has a stable economy."},
    {"word": "Strategy", "translation": "strategiya", "level": "B1", "example": "The company changed its marketing strategy."},
    {"word": "Struggle", "translation": "kurashmoq", "level": "B1", "example": "Many families struggle to pay rent."},
    {"word": "Sufficient", "translation": "yetarli", "level": "B1", "example": "We don't have sufficient evidence yet."},
    {"word": "Suggest", "translation": "taklif qilmoq", "level": "B1", "example": "I suggest we leave early tomorrow."},
    {"word": "Urban", "translation": "shahar", "level": "B1", "example": "Urban areas are growing faster than rural ones."},
]

# Kengaytirilgan C1-C2 (Advanced) darajasidagi so'zlar bazasi
VOCAB_C1_C2 = [
    {"word": "Ambiguous", "translation": "noaniq, ikki ma'noli", "level": "C1", "example": "The instructions were ambiguous and confusing."},
    {"word": "Advocate", "translation": "yoqlamoq, tarafdor", "level": "C1", "example": "She advocates for equal rights."},
    {"word": "Arbitrary", "translation": "o'zboshimchalik bilan", "level": "C1", "example": "The decision seemed completely arbitrary."},
    {"word": "Coherent", "translation": "izchil, mantiqiy", "level": "C1", "example": "Write a coherent argument in your essay."},
    {"word": "Compelling", "translation": "ishonarli, ta'sirli", "level": "C1", "example": "He gave a compelling argument for change."},
    {"word": "Comprehensive", "translation": "har tomonlama", "level": "C1", "example": "The report gives a comprehensive overview."},
    {"word": "Conceive", "translation": "tasavvur qilmoq", "level": "C1", "example": "It's hard to conceive of life without technology."},
    {"word": "Consolidate", "translation": "mustahkamlamoq", "level": "C1", "example": "The company consolidated its position in the market."},
    {"word": "Contentious", "translation": "bahsli", "level": "C1", "example": "Immigration remains a contentious issue."},
    {"word": "Contradict", "translation": "ziddiyat qilmoq", "level": "C1", "example": "His statement contradicts the earlier report."},
    {"word": "Conventional", "translation": "an'anaviy", "level": "C1", "example": "She rejected conventional methods of teaching."},
    {"word": "Correlate", "translation": "bog'liq bo'lmoq", "level": "C1", "example": "Income tends to correlate with education level."},
    {"word": "Counterpart", "translation": "hamkasb, o'xshashi", "level": "C1", "example": "She met her counterpart from another company."},
    {"word": "Credible", "translation": "ishonchli", "level": "C1", "example": "We need credible evidence to support this theory."},
    {"word": "Cumulative", "translation": "yig'ma, kumulyativ", "level": "C1", "example": "The cumulative effect of pollution is severe."},
    {"word": "Deduce", "translation": "xulosa chiqarmoq", "level": "C1", "example": "We can deduce the cause from the evidence."},
    {"word": "Deficient", "translation": "yetishmovchi", "level": "C1", "example": "The diet is deficient in essential vitamins."},
    {"word": "Discrepancy", "translation": "nomuvofiqlik", "level": "C1", "example": "There is a discrepancy between the two reports."},
    {"word": "Discern", "translation": "ajratib olmoq", "level": "C1", "example": "It's hard to discern the truth from rumours."},
    {"word": "Disparity", "translation": "tafovut", "level": "C1", "example": "There is a wide disparity in income levels."},
    {"word": "Disseminate", "translation": "tarqatmoq", "level": "C1", "example": "The internet helps disseminate information quickly."},
    {"word": "Distinct", "translation": "aniq farqli", "level": "C1", "example": "The two theories are quite distinct."},
    {"word": "Elaborate", "translation": "batafsil bayon qilmoq", "level": "C1", "example": "Could you elaborate on your last point?"},
    {"word": "Empirical", "translation": "amaliy, tajribaviy", "level": "C1", "example": "The study is based on empirical evidence."},
    {"word": "Endorse", "translation": "qo'llab-quvvatlamoq", "level": "C1", "example": "The scientist endorsed the new policy."},
    {"word": "Entail", "translation": "talab qilmoq, o'z ichiga olmoq", "level": "C1", "example": "The job entails a lot of travelling."},
    {"word": "Explicit", "translation": "aniq ifodalangan", "level": "C1", "example": "The contract is very explicit about payment terms."},
    {"word": "Extrapolate", "translation": "ekstrapolyatsiya qilmoq", "level": "C1", "example": "We can extrapolate future trends from this data."},
    {"word": "Facilitate", "translation": "yengillashtirmoq", "level": "C1", "example": "Technology facilitates communication across the world."},
    {"word": "Feasible", "translation": "amalga oshirish mumkin", "level": "C1", "example": "Is it feasible to finish the project by Friday?"},
    {"word": "Hypothesis", "translation": "gipoteza", "level": "C1", "example": "Scientists tested their hypothesis in the lab."},
    {"word": "Implicit", "translation": "yashirin, nazarda tutilgan", "level": "C1", "example": "There was an implicit agreement between them."},
    {"word": "Incentive", "translation": "rag'bat", "level": "C1", "example": "Tax cuts are an incentive for businesses to invest."},
    {"word": "Inevitable", "translation": "muqarrar", "level": "C1", "example": "Change is inevitable in a fast-growing economy."},
    {"word": "Infer", "translation": "xulosa chiqarmoq", "level": "C1", "example": "From his tone, I inferred he was upset."},
    {"word": "Innate", "translation": "tug'ma", "level": "C1", "example": "Some believe language ability is innate."},
    {"word": "Integral", "translation": "ajralmas qism", "level": "C1", "example": "Practice is integral to learning a language."},
    {"word": "Intrinsic", "translation": "ichki, tabiiy", "level": "C1", "example": "The book has intrinsic value beyond its price."},
    {"word": "Marginal", "translation": "ahamiyatsiz, chekka", "level": "C1", "example": "The improvement was only marginal."},
    {"word": "Meticulous", "translation": "puxta, ehtiyotkor", "level": "C1", "example": "She is meticulous about her research."},
    {"word": "Mitigate", "translation": "yumshatmoq", "level": "C1", "example": "The government took steps to mitigate the damage."},
    {"word": "Notion", "translation": "tushuncha, fikr", "level": "C1", "example": "The notion of success varies between cultures."},
    {"word": "Nuance", "translation": "nozik farq", "level": "C1", "example": "A good translator understands cultural nuances."},
    {"word": "Paradox", "translation": "paradoks", "level": "C1", "example": "It's a paradox that more choice can cause more stress."},
    {"word": "Perpetuate", "translation": "abadiylashtirmoq", "level": "C1", "example": "The media can perpetuate stereotypes."},
    {"word": "Plausible", "translation": "ishonarli, mumkin bo'lgan", "level": "C1", "example": "That's a plausible explanation for the delay."},
    {"word": "Precede", "translation": "oldin bo'lmoq", "level": "C1", "example": "A warning usually precedes a storm."},
    {"word": "Precedent", "translation": "presedent", "level": "C1", "example": "The court's decision set an important precedent."},
    {"word": "Premise", "translation": "asos, taxmin", "level": "C1", "example": "The whole argument is based on a false premise."},
    {"word": "Prevalent", "translation": "keng tarqalgan", "level": "C1", "example": "Obesity is becoming more prevalent worldwide."},
    {"word": "Proponent", "translation": "tarafdor", "level": "C1", "example": "She is a strong proponent of renewable energy."},
    {"word": "Rationale", "translation": "asos, mantiq", "level": "C1", "example": "What is the rationale behind this decision?"},
    {"word": "Refute", "translation": "rad etmoq", "level": "C1", "example": "The scientist refuted the earlier claims."},
    {"word": "Reinforce", "translation": "mustahkamlamoq", "level": "C1", "example": "Practice reinforces what you learn in class."},
    {"word": "Robust", "translation": "mustahkam, barqaror", "level": "C1", "example": "The economy showed robust growth this year."},
    {"word": "Scrutinize", "translation": "sinchiklab tekshirmoq", "level": "C1", "example": "Auditors scrutinized the company's accounts."},
    {"word": "Skeptical", "translation": "shubhali qaraydigan", "level": "C1", "example": "Many people are skeptical about the new policy."},
    {"word": "Speculate", "translation": "taxmin qilmoq", "level": "C1", "example": "Analysts speculate that prices will rise."},
    {"word": "Subsequent", "translation": "keyingi", "level": "C1", "example": "Subsequent studies confirmed the first results."},
    {"word": "Substantiate", "translation": "asoslamoq", "level": "C1", "example": "She couldn't substantiate her claims with evidence."},
    {"word": "Subtle", "translation": "nozik, sezilmas", "level": "C1", "example": "There is a subtle difference between the two words."},
    {"word": "Superficial", "translation": "yuzaki", "level": "C1", "example": "His knowledge of the topic is quite superficial."},
    {"word": "Tangible", "translation": "aniq, sezilarli", "level": "C1", "example": "The project brought tangible benefits to the town."},
    {"word": "Ubiquitous", "translation": "hamma joyda uchraydigan", "level": "C1", "example": "Smartphones have become ubiquitous today."},
    {"word": "Underlying", "translation": "asosiy, yashirin", "level": "C1", "example": "We must address the underlying cause of the problem."},
    {"word": "Undermine", "translation": "zaiflashtirmoq", "level": "C1", "example": "Corruption undermines public trust in government."},
    {"word": "Unprecedented", "translation": "misli ko'rilmagan", "level": "C1", "example": "The city faced unprecedented levels of rainfall."},
    {"word": "Validate", "translation": "tasdiqlamoq", "level": "C1", "example": "The results were validated by independent researchers."},
    {"word": "Verify", "translation": "tekshirib tasdiqlamoq", "level": "C1", "example": "Please verify your identity before continuing."},
    {"word": "Viable", "translation": "amalga oshirish mumkin bo'lgan", "level": "C1", "example": "Is solar power a viable option for this region?"},
    {"word": "Volatile", "translation": "beqaror", "level": "C1", "example": "The stock market has been very volatile recently."},
    {"word": "Advent", "translation": "paydo bo'lish", "level": "C1", "example": "The advent of the internet changed communication."},
    {"word": "Aftermath", "translation": "oqibat", "level": "C1", "example": "The aftermath of the storm was devastating."},
    {"word": "Assert", "translation": "qat'iy aytmoq", "level": "C1", "example": "She asserted her right to speak first."},
    {"word": "Attain", "translation": "erishmoq", "level": "C1", "example": "Few students attain such high scores."},
    {"word": "Attribute", "translation": "bog'lamoq, xususiyat", "level": "C1", "example": "He attributes his success to hard work."},
    {"word": "Coincide", "translation": "mos kelmoq", "level": "C1", "example": "Her visit coincided with the festival."},
    {"word": "Constitute", "translation": "tashkil etmoq", "level": "C1", "example": "Women constitute half of the workforce."},
    {"word": "Contemplate", "translation": "chuqur o'ylamoq", "level": "C1", "example": "She contemplated moving to another country."},
    {"word": "Convey", "translation": "yetkazmoq", "level": "C1", "example": "The letter conveyed a sense of urgency."},
    {"word": "Depict", "translation": "tasvirlamoq", "level": "C1", "example": "The painting depicts a rural village."},
    {"word": "Derive", "translation": "kelib chiqmoq", "level": "C1", "example": "Many English words derive from Latin."},
    {"word": "Discrete", "translation": "alohida", "level": "C1", "example": "The data was divided into discrete categories."},
    {"word": "Dispel", "translation": "yo'qotmoq, tarqatmoq", "level": "C1", "example": "The results dispelled our doubts."},
    {"word": "Diverge", "translation": "ajralmoq, farqlanmoq", "level": "C1", "example": "Their opinions began to diverge over time."},
    {"word": "Domain", "translation": "soha", "level": "C1", "example": "Artificial intelligence is a growing domain."},
    {"word": "Dynamic", "translation": "dinamik, faol", "level": "C1", "example": "The city has a dynamic and youthful population."},
    {"word": "Enhance", "translation": "kuchaytirmoq, yaxshilamoq", "level": "C1", "example": "Good lighting can enhance a photograph."},
    {"word": "Erode", "translation": "yemirmoq", "level": "C1", "example": "Trust between the two countries has eroded."},
    {"word": "Exemplify", "translation": "misol bilan ko'rsatmoq", "level": "C1", "example": "This case exemplifies a common problem."},
    {"word": "Exploit", "translation": "foydalanmoq, ekspluatatsiya qilmoq", "level": "C1", "example": "The company exploited a gap in the market."},
    {"word": "Formulate", "translation": "shakllantirmoq", "level": "C1", "example": "The team formulated a new strategy."},
    {"word": "Fundamental", "translation": "asosiy, tub", "level": "C1", "example": "Trust is fundamental to any relationship."},
    {"word": "Holistic", "translation": "yaxlit", "level": "C1", "example": "The clinic takes a holistic approach to health."},
    {"word": "Impede", "translation": "to'sqinlik qilmoq", "level": "C1", "example": "Poor infrastructure impedes economic growth."},
    {"word": "Inherent", "translation": "tabiiy, ichki", "level": "C1", "example": "There are inherent risks in any investment."},
    {"word": "Manifest", "translation": "namoyon bo'lmoq", "level": "C1", "example": "Stress can manifest as physical illness."},
    {"word": "Paradigm", "translation": "paradigma, namuna", "level": "C1", "example": "The internet created a new paradigm for business."},
    {"word": "Trigger", "translation": "sabab bo'lmoq, qo'zg'atmoq", "level": "C1", "example": "The announcement triggered a wave of protests."},
]
